"""empty message

Revision ID: 315f30caacf2
Revises: e5b1499beb1a
Create Date: 2021-05-09 03:55:36.689033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315f30caacf2'
down_revision = 'e5b1499beb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'registro', ['identificacion'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registro', type_='unique')
    # ### end Alembic commands ###
