"""empty message

Revision ID: 6eacae2a4edd
Revises: e2c86ad35888
Create Date: 2021-05-06 01:56:48.045609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eacae2a4edd'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido1', sa.String(length=120), nullable=False),
    sa.Column('apellido2', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.Column('estado_civil', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=False),
    sa.Column('canton', sa.String(length=120), nullable=False),
    sa.Column('distrito', sa.String(length=120), nullable=False),
    sa.Column('dir_exacta', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'identificacion'),
    sa.UniqueConstraint('apellido1'),
    sa.UniqueConstraint('apellido1'),
    sa.UniqueConstraint('fecha_nacimiento'),
    sa.UniqueConstraint('fecha_nacimiento'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('tipo_id'),
    sa.UniqueConstraint('tipo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_persona')
    # ### end Alembic commands ###
