"""empty message

Revision ID: 730c96edd8e8
Revises: 7926d8be0f42
Create Date: 2021-05-12 19:02:07.944718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730c96edd8e8'
down_revision = '7926d8be0f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registro_fecha_nacimiento_key', 'registro', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('registro_fecha_nacimiento_key', 'registro', ['fecha_nacimiento'])
    # ### end Alembic commands ###
