"""empty message

Revision ID: 89f9946f4aa9
Revises: 730c96edd8e8
Create Date: 2021-05-12 19:48:35.089424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f9946f4aa9'
down_revision = '730c96edd8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registro_telefono_key', 'registro', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('registro_telefono_key', 'registro', ['telefono'])
    # ### end Alembic commands ###
