"""empty message

Revision ID: b55aeb9365dd
Revises: 6eacae2a4edd
Create Date: 2021-05-06 04:56:19.808696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55aeb9365dd'
down_revision = '6eacae2a4edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido1', sa.String(length=120), nullable=False),
    sa.Column('apellido2', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.Column('estado_civil', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=False),
    sa.Column('canton', sa.String(length=120), nullable=False),
    sa.Column('distrito', sa.String(length=120), nullable=False),
    sa.Column('dir_exacta', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'identificacion'),
    sa.UniqueConstraint('apellido1'),
    sa.UniqueConstraint('apellido1'),
    sa.UniqueConstraint('fecha_nacimiento'),
    sa.UniqueConstraint('fecha_nacimiento'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('tipo_id'),
    sa.UniqueConstraint('tipo_id')
    )
    op.drop_table('registro_persona')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_persona',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identificacion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido1', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido2', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('estado_civil', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('provincia', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('canton', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('distrito', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('dir_exacta', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'identificacion', name='registro_persona_pkey'),
    sa.UniqueConstraint('apellido1', name='registro_persona_apellido1_key'),
    sa.UniqueConstraint('fecha_nacimiento', name='registro_persona_fecha_nacimiento_key'),
    sa.UniqueConstraint('nombre', name='registro_persona_nombre_key'),
    sa.UniqueConstraint('telefono', name='registro_persona_telefono_key'),
    sa.UniqueConstraint('tipo_id', name='registro_persona_tipo_id_key')
    )
    op.drop_table('registro')
    # ### end Alembic commands ###
