"""empty message

Revision ID: d2c00221aa20
Revises: 315f30caacf2
Create Date: 2021-05-11 03:52:06.436499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c00221aa20'
down_revision = '315f30caacf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identificacion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido1', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido2', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('estado_civil', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('canton', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('distrito', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('dir_exacta', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'identificacion', name='registro_pkey'),
    sa.UniqueConstraint('apellido1', name='registro_apellido1_key'),
    sa.UniqueConstraint('fecha_nacimiento', name='registro_fecha_nacimiento_key'),
    sa.UniqueConstraint('identificacion', name='registro_identificacion_key'),
    sa.UniqueConstraint('nombre', name='registro_nombre_key'),
    sa.UniqueConstraint('telefono', name='registro_telefono_key'),
    sa.UniqueConstraint('tipo_id', name='registro_tipo_id_key')
    )
    # ### end Alembic commands ###
