"""empty message

Revision ID: dbad7ee8884b
Revises: e5b1499beb1a
Create Date: 2021-05-08 03:59:33.581054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbad7ee8884b'
down_revision = 'e5b1499beb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('registro', sa.Column('password', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'registro', ['email'])
    op.create_unique_constraint(None, 'registro', ['identificacion'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registro', type_='unique')
    op.drop_constraint(None, 'registro', type_='unique')
    op.drop_column('registro', 'password')
    op.drop_column('registro', 'email')
    # ### end Alembic commands ###
